version: 2.1

orbs:
  python: circleci/python@0.2.1
  browser-tools: circleci/browser-tools@1.0.0

jobs:
  build-and-test:
    executor: python/default
    parameters:
      replace-existing:
        type: boolean
        default: false
        description: >
          If there is an existing installation of Google Chrome, replace it
          with the latest stable release?
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Install Chrome and driver
          command: sh ./project/setup.sh

      - browser-tools/install-chromedriver
      - run:
          command: python wms_test.py
          name: wms_test.py

workflows:
  main:
    jobs:
      - build-and-test
