version: 2.1

orbs:
  python: circleci/python@0.2.1
  browser-tools: circleci/browser-tools@x.y

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: python wms_test.py
          name: wms_test.py

workflows:
  main:
    jobs:
      - build-and-test
