version: 2.1

orbs:
  python: circleci/python@0.2.1
  browser-tools: circleci/browser-tools@1.0.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: >
        if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi


        # download chrome

        curl --silent --show-error --location --fail --retry 3 \
          --output google-chrome-stable_current_amd64.deb \
          https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

        # setup chrome installation

        $SUDO dpkg -i google-chrome-stable_current_amd64.deb || $SUDO apt-get
        -fy install


        rm -rf google-chrome-stable_current_amd64.deb
        $SUDO apt-get -f install


        $SUDO sed -i 's|HERE/chrome"|HERE/chrome" --disable-setuid-sandbox
        --no-sandbox|g' \
            "/opt/google/chrome/google-chrome"

        # verify version

        google-chrome --version
          name: Install Google Chrome
      - browser-tools/install-chromedriver
      - run:
          command: python wms_test.py
          name: wms_test.py

workflows:
  main:
    jobs:
      - build-and-test
